var m,p="undefined"==typeof browser,r=0<navigator.userAgent.indexOf("Edge/"),t=0<navigator.userAgent.indexOf("Firefox/"),u=0<navigator.userAgent.indexOf("OPR/");p&&(browser=chrome);
var v,aa,ba,ca,da=t?69:r?77:66,ea=t?220:150,x=["127.0.0.1:1001","0.1.0.1:1001"],fa=/(?:chrome|about|chrome-extension|ms-browser-extension|moz-extension):/,ga=["main_frame","sub_frame"],y="main_frame sub_frame image object xmlhttprequest other".split(" "),B=["image","object","xmlhttprequest","other"],ha="origin referer dnt cookie user-agent accept-encoding".split(" "),ia=[301,302,303,307],ja=["*://*/*","ftp://*/*","file:///*"],ka=["*://*/*"],la=["*://*/*"],ma=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,na=browser.runtime.getURL("captured.html"),
oa=browser.runtime.getURL("").slice(0,-1),pa=browser.extension.getBackgroundPage().location.href,qa=/^https?:\/\/(?:www\.youtube\.com\/|www\.facebook\.com\/(?:.+\/(?:videos|posts|permalink)\/(?:\w+\.\d+\/)?\d+\b|video\/\w+\/async\b|video\/embed\b|watch\b)|player\.vimeo\.com\/video\/\d+)/i,ra=/^(?:\b[^.]+?\.)*?(?:youtube\.com|googlevideo\.com|youtube\.googleapis\.com|docs\.google\.com|drive\.google\.com)$/i,sa=/^(?:\b[^.]+?\.)?(?:vimeo\.com|.*\.vimeocdn\.com)$/i,ta=/^(?:www\.facebook\.com|.*\.fbcdn\.net)$/i,
ua=/^\/video\/\w+\/async\/(\d+)\//,va=/\/(?:.+\/(?:videos|posts|permalink)\/(?:\w+\.\d+\/)?|video\/embed\?.*?\bvideo_id=|watch\/?\?.*?\bv=)(\d+)\b/,wa=[[118,117,119,120,121]],xa={16:1,17:2,18:4,45:8,46:16},ya={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},za={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|SRT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|F4M|TTML","text/x-javascript":"JS|JSON",
"text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ",
"application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP",
"video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI",
"audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR",
"image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"},C=Function.call.bind(Array.prototype.slice),Aa=Function.apply.bind(Array.prototype.push);function Ba(){this.c=this.constructor.prototype.u++}Ba.prototype.u=1;function Ca(a,b,c,d){this.id=a;this.port=b;c&&(this.c=c.toLowerCase());d&&(this.b=d)}Ca.prototype.a=0;function Da(a,b,c){this.id=[a,b].toString();this.a=0>c?null:[a,c].toString()}
function F(a,b,c,d,e,f){if(a){var g=["MSG#",a,"#",b,"#",c,"#",d];this.m=a;this.l=b;this.w=c;this.g=d;this.a=e||[];this.h=g;if(e)for(a=0;a<e.length;a++)g.push(":",e[a]||0);if(f)for(var h in f)if(e=f[h],null!=e)if(g.push(",",h,"="),"string"==typeof e){b=a=e.length;for(c=0;c<b;)d=e.charCodeAt(c++),128<=d&&(2048<=d?(a+=2,d-55296&56320||c++):a++);g.push(a,":",e)}else e instanceof Blob?g.push(e.size,":",e):g.push(e)}else this.i=new FileReader}m=F.prototype;m.o=null;m.X=null;m.B=null;m.U=!1;
function Ea(a){a.U||(a.h.push(";"),a.U=!0);return a.h.join("")}function Fa(a){a.U||(a.h.push(";"),a.U=!0);return new Blob(a.h)}function Ga(a,b,c){a.U?a.B(a):(b.a=c||0,b.b=0,a.i.onload=a.Qa.bind(a,b),G(a,b,0,50))}
m.Qa=function(a){for(var b=this.i.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.B(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.B(this);this.m=parseInt(d[1]);this.l=parseInt(d[2]);this.w=parseInt(d[3]);this.g=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return G(this,a,b.length,100);a.b=4}f=e.length+
1;this.a=d=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),g=d.shift(),f=g.length,e=!1;if(d.length)f++;else{if(!c.length)return G(this,a,b.length,25);e=!0}d=g.split("=",3);if(2!=d.length)return this.B(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.f=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,f+b);a.size==
b?this.i.readAsText(a):this.B(this);return;case 3:return this[a.f]=b,a.a+=a.c,a.b++,G(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.B(this)}a.a++;break;case 5:this.U=!0;this.X(this);a.size>a.a&&(b=new F,b.X=this.X,b.B=this.B,Ga(b,a,a.a));return}};function G(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.i.readAsBinaryString(b.slice(e,c+d)):a.B(a)}
function H(){if(v){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.Aa=[];this.L=!1;this.M=this.ga=null;this.c={};this.u={};this.a={};this.h={};this.b={};this.l={};this.g={};this.f={};this.D={};this.W="";this.ea=!0;this.Na=this.za=this.Ma=1;this.C={};this.i=null;this.N=1;this.m=!1;this.F=0;this.I=null;this.w=u;this.K=0;this.ya=null;this.V=this.J=!1;p&&browser.browserAction.disable();t||ja.push("about:blank");t||ka.push("about:blank");
browser.windows.onCreated.addListener(this.Ga);browser.windows.onRemoved.addListener(this.Ha);browser.windows.onFocusChanged.addListener(this.eb);browser.tabs.onActivated.addListener(this.Xa);browser.tabs.onUpdated.addListener(this.$a);browser.tabs.onRemoved.addListener(this.Za);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.Ya);this.xa();this.ia();Ha(this,!0)}}
function Ha(a,b){var c=a.c,d=a.C={};browser.contextMenus.removeAll();for(var e=0;e<Ia.length;e++){var f=Ia[e];f[0]&&(t?b||c[f[1]]:1)&&(d[e]=browser.contextMenus.create({title:Ja(f[2]),contexts:f[3].split(","),onclick:f[4].bind(a),documentUrlPatterns:f[5]||ja,enabled:!0}))}}function Ka(a,b,c,d,e){a=a.g;return b in a?a[b]:a[b]=new Ca(b,c,d,e)}function La(a,b){var c=a.f,d=b.requestId;c[d]=b;var e=b.id;e||(e=b.id=r?String(a.Na++):d);e!=d&&(c[e]=b,c=a.h[[b.tabId,b.frameId]])&&(c.b=e)}
function Ma(a,b,c,d){var e=[b,c].toString();a=a.h;return e in a?a[e]:a[e]=new Da(b,c,d)}function Na(a){var b=new Ba;return a.l[b.c]=b}function I(a,b){var c=a.l[b];c&&delete a.l[b];return c}m=H.prototype;
m.ia=function(){var a=this.F%(x.length+1);if(a<x.length)this.ga=a=new WebSocket("ws://"+x[a]+"/?cid="+Math.random().toString().substr(2,9),"plugin.v3.internetdownloadmanager.com"),a.onopen=this.oa,a.onclose=this.O,a.onmessage=this.Wa,1==a.readyState?this.oa():3==a.readyState&&this.O();else{this.M=a=browser.runtime.connectNative("com.tonec.idm");try{a.postMessage("")}catch(b){a=null}a?(a.onDisconnect.addListener(this.O),a.onMessage.addListener(this.Sa),this.oa()):this.O()}};
m.oa=function(){this.m=!0;this.za=1;var a=[6,15,this.w?6:7,0],b={};b[112]=ba;b[113]=aa;b[114]="Chrome_RenderWidgetHostHWND";if(587202560<=v){var c=browser.i18n.getUILanguage().replace("_","-");"sr"==c&&(c+="-Cyrl-CS");b[116]=c}J(this,2,1,0,a,b)};
m.O=function(){browser.runtime.lastError;this.ga=this.M=null;if(this.m){this.m=!1;this.D={};for(var a=this.Aa,b=0;b<a.length;b++){var c=a.splice(b--,1).pop(),d=c.splice(0,2).pop();r&&c.splice(1);d.removeListener.apply(d,c)}this.L=!1;this.I=null;p&&browser.browserAction.disable()}a=++this.F;b=x.length+1;c=a/b;120>c&&(1==c&&this.ea&&this.ha(),!a||a%b?this.ia():window.setTimeout(this.ia,5E3*c))};m.Wa=function(a){var b=new F;b.X=this.Ea;b.B=this.O;Ga(b,a.data)};
m.Sa=function(a){var b=new F;b.X=this.Ea;b.B=this.O;Ga(b,new Blob([a]))};function J(a,b,c,d,e,f){if(!a.m)return!1;var g=a.za++;b=new F(g,b,c,d,e,f);if(c=a.ga)c.send(Fa(b));else try{a.M.postMessage(Ea(b))}catch(h){return a.O(),!1}d&1&&(a.D[g]=b);return!0}
function Qa(a,b){var c=a.f;if(b.a){var d=b.a[6],e=c[d];if(e){var f=e.type;return!f||"image"==f||e.f?(b.o=e.port.id,b.N=d,!0):!1}}var g=a.a,h=a.g,k=b[6],l=b[17],n=b[50],q=b[7],A,D;for(d in c){var e=c[d],w=e.url;if(w){if(w==k||w==l)if(f=e.type,!f||"image"==f||e.f)return b.o=e.port.id,b.N=parseInt(d),!0;w==n&&(D=e.port.id)}}for(d in h)if(c=h[d],w=c.b){if(w==k||w==l||w==n)if(e=c.port,q&&(f=g[e.tabId])&&f.j!=q&&(e=null),e)return b.o=e.id,!0;w==q&&(A=c.port.id)}return null!=D?(b.o=D,!0):null!=A?(b.o=A,
!0):!1}m.Ca=function(a,b,c,d){if(b)return d?(b=(c=d.shift())&&this.a[c.id])?a.o=b.id:null:null;if(null!=a.o)return a.o;if(a.a){var e=a.a[7];if(e&&this.u[e])return a.o=e}if(Qa(this,a))return a.o;d=this.u;var f=a[50],g=a[7];for(e in d){b=d[e];if(b.j==f){a.o=e;break}null==a.o&&b.j==g&&(a.o=e)}if(null!=a.o)return a.o;g&&browser.tabs.query({url:g},Ra(this,a,!0,c));return null};
m.ka=function(a,b,c,d,e,f){var g=a.tabId,h=a.Z,k=a.A,l=a.b,n;if(void 0===b){if(f=new L(this,a,!0),null==k&&(a.a?(browser.tabs.get(g,O(f,2)),browser.windows.getLastFocused(O(f,3))):(k=this.a[g],a.A=k&&k.A)),null==h&&a.j?browser.webNavigation.getAllFrames({tabId:g},O(f,5)):h&&null==l&&browser.webNavigation.getFrame({frameId:h,tabId:g},O(f,4)),P(f))return}else if(b&&(c&&0<=c.index?a.A=c.windowId:d&&(a.A=d.id),e&&(n=e.parentFrameId),f))for(d=a.j,e=d.includes("#")&&Sa(d),k=f.length-1;0<=k;k--)if(b=f[k],
c=b.j,!b.gb&&b.frameId&&(c==d||e&&c==e)){h=a.Z=b.frameId;n=b.parentFrameId;break}if(null==h)a.j||a.postMessage([11,g,null,!0]);else{f=[g,h].toString();0<=n&&(l=a.b=[g,n].toString());if(b=this.h[f])a.i=b.b,a.c=b.c,(c=b.P)&&a.j!=c&&(a.P=c),!l&&b.a&&(a.b=b.a);this.a[f]=a;l=this.c;g=[11,g,h,!a.j,a.c];if((n=a.m)&&a.c)for(h=wa[n-1],g.push(n),k=0;k<h.length;k++)g.push(l[h[k]]);a.postMessage(g)}};
m.ca=function(a,b,c,d,e,f,g,h){var k=Ta(a,!0);if(!k)return 0;if(1==k){if(!g)return Q(a,Ra(this,a,b,c,d,e,f,!0)),-1;"object"==typeof h&&(h=R(h))}g=[k];k={};k[6]=a;k[50]=b;k[7]=c;k[8]=d;k[100]=e;k[102]=f;k[51]=h;k[54]=navigator.userAgent;J(this,14,1,0,g,k);return 3};
m.Ka=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new L(this,a,b,c,!0);c.Y&&!c.Ia&&Q(c.Y,O(f,4));for(var g=0;g<a.length;g++)Q(a[g][0],O(f,5+g));if(P(f))return}e&&(c.Ia=R(e));for(g=0;g<a.length;g++)a[g][5]=R(arguments[g+5]);var f=0,g=[a.length],h={8:4};h[54]=navigator.userAgent;h[7]=c.Y;h[110]=c.R;h[111]=c.Ia;1<a.length&&(J(this,15,1,f,g,h),f=16,h={});for(var g=[0],k;k=a.shift();)h[6]=k[0],h[100]=k[2],h[102]=k[3],h[50]=k[4],h[51]=k[5],J(this,14,1,f,g,h)};
function Q(a,b){if(r&&a.startsWith("ftp:"))b([]);else{var c={url:a};ca&&(c.firstPartyDomain=null);browser.cookies.getAll(c,b)}}function S(a,b,c,d){a=a.c;(b=b[c])?(b=b.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*?"),d&&(b=b.replace(/~/g,"(?:\\b[^.]+?\\.)?")),b="^(?:"+b.replace(/\|{2,}/g,"|")+")$"):b="(?!)";a[c]=new RegExp(b,"i")}
function Ua(a,b,c,d,e,f,g,h){if(!d||a.c[-8]){var k=a.a[b];if(k){var l=Na(a),n=l.c;l.tabId=b;l.port=k;l.J=c;l.f=0;l.L=[];if(k=d&&!!e)l.W=!0,l.ea=e,l.D=f,l.F=g,l.K=h,e.a||Va(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)");l.C=Wa(a,b,[12,n,c,k,e]);l.M=0;l.C||I(a,n)}}}
m.T=function(a,b,c){if(4294967295==a)this.i=null,c=!0;else{var d=this.g[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.T.bind(this,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&J(this,8,1,32,[a])};function Xa(a,b){var c=a.b[b];if(c&&c.$){var d=c.border,e=c.scale;J(a,7,1,0,[b,Math.round((c.fa+d)*e),Math.round((c.va+d)*e),Math.round((c.width-d-c.sa)*e),Math.round((c.height-d)*e)])}}
function Ya(a,b,c,d){var e=a.g[b],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var g,h,k,l,n;c&&(g=c[0],h=c[1],k=c[2]||g+1,l=c[3]||h+1,n=c[4],c=e.port.h)&&(g+=c[0],h+=c[1],k=Math.min(k+c[0],c[2]),l=Math.min(l+c[1],c[3]));J(a,9,1,f,[b,g,h,k,l,n])}
m.da=function(a){var b=this.b,c=[];if(a)(a=b[a])&&(a.G||a.H||c.push(a.v));else for(var d in b)a=b[d],a.G||a.H||c.push(a.v);if(c.length){b=[15,null,null];a={};var e=this.g;for(d in e){var f=e[d];f.a&&0<=c.indexOf(f.port.tabId)&&(f.c?(f=f.port,f.a||Va(this,f,null,a),b[2]=d,f.postMessage(b)):Ya(this,d,null,!0))}}};function Za(a,b){var c=a.b[b];c&&!c.H&&T(a,c.v,void 0)}function T(a,b,c){var d=c?0:2;c=c?32:64;var e=a.g,f;for(f in e){var g=e[f];g.a&&g.port.tabId==b&&g.a!=d&&(g.a=d,J(a,8,1,c,[f]))}}
function U(a,b,c,d){var e=a.K,f=(e&b)!=((c?63:32)&b);a.K=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.J=0!=c&&(e&c)==c,e=a.V=0!=b&&(e&b)==b,a.ya=(c||e)&&d||null)}m.wa=function(a,b,c,d){var e=this.b[a];if(e)if(d)e.H&&window.clearTimeout(e.H),e.H=window.setTimeout(this.wa.bind(this,a,b,c),d);else if(e.H=null,b&&(browser.windows.get(a,this.S),browser.tabs.query({windowId:a,active:!0},this.S)),c){if((a=this.b[a])&&!a.H){a=a.v;b=this.g;for(var f in b)c=b[f],c.a&&c.port.tabId==a&&1==c.a&&J(this,8,1,1152,[f])}}else this.da(a)};
m.S=function(a,b){a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,d=this.b[c];if(d){if(a.windowId){if(d.na&&fa.test(a.url))return;d.v=a.id;a.width&&(d.ua=a.width);a.height&&(d.ta=a.height)}else{var e=b?d.scale=this.N:d.scale,f="fullscreen"==a.state,g=!b&&f!=d.G;d.G=f;d.Da="maximized"==a.state;d.ma="minimized"==a.state;r?(d.width=Math.round(a.width/e),d.height=Math.round(a.height/e),d.left=Math.round(a.left/e),d.top=Math.round(a.top/e)):(d.width=a.width,d.height=a.height,d.left=a.left,
d.top=a.top);g&&(f?Za(this,c):this.da(c))}g=d.ua;e=d.ta;if(g&&e){var h=d.width,f=d.height;if(!d.na&&!d.ma){if(g>h||e>f)return browser.windows.get(c,this.S);d.na=!0}g=h-g;h=g/2;0<=h&&20>=h?(d.border=h,d.fa=d.sa=0):(h=d.border,t||u?d.fa=g-2*h:d.sa=g-2*h);e=f-e-2*h;e<=ea&&(d.va=e)}b||Xa(this,c);return d}}};
function Va(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.b];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.Pa,c[2]=d,c[3]=b.Z,c[4]=d?null:b.j,c[5]=d?null:b.P,f.postMessage(c)}function Wa(a,b,c){a=a.a;b=[b,null].toString();var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
m.la=function(a){var b={file:"content.js",runAt:"document_start",allFrames:!0};620756992<=v&&(b.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{browser.tabs.executeScript(a.shift().id,b,V)}catch(c){}else try{browser.tabs.executeScript(a.id||a,b,V)}catch(c){}};function $a(a,b,c,d){var e=17,f=[b.A,b.$,b.width,b.height,b.left,b.top,b.scale],g={};b.Da&&(e|=256);b.ma&&(e|=512);null!=c&&(e|=c?2048:1024);d&&(g[117]=d);J(a,6,2,e,f,g)}
m.xa=function(a,b){if(b)for(;b.length;){var c=b.shift(),d=this.S(c,!0)||this.Ga(c);$a(this,d,c.focused,c.title)}else if(!a){c=this.xa.bind(this,!0);try{browser.windows.getAll({windowTypes:["normal","popup"]},c)}catch(e){browser.windows.getAll(c)}}};
m.ja=function(a,b){if(!this.m)return ab(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d;if(a.menuItemId==this.C[4])return browser.downloads.search({query:[c]},this.Oa.bind(this,c));if(a.menuItemId==this.C[1])c=a.frameUrl,c&&"about:blank"!=c||(c=d,e=null);else if(!c){var c=a.srcUrl,f=this.a[[b.id,a.frameId].toString()];if(f){var g=Na(this);g.tabId=b.id;g.port=f;g.I=c;g.V=e;g.Y=d;g.g=4;return f.postMessage([18,g.c,c])}}c&&this.ca(c,e,d,4)};
m.Ba=function(a,b){if(!this.m)return ab(b.id,"cannot_contact_idm");Ua(this,b.id,a.menuItemId==this.C[2])};m.Oa=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.ca(a,d||e,null,4)};
m.Ta=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=a.portId_||this.Ma++);var d=b.id,e="top"==a.name;a.tabId=d;a.A=0>b.index?null:b.windowId;a.f=!0;a.g=!1;a.a=e;a.Z=e?0:a.sender.frameId;a.l=0;a.j=a.sender.url||e&&b.url||null;a.P=null;this.u[c]=a;e&&(this.a[d]=a);a.j&&(b=new URL(a.j),ra.test(b.hostname)&&(a.m=1));a.onMessage.addListener(this.Ua.bind(this,a));a.onDisconnect.addListener(this.ba);this.ka(a)}};
m.ba=function(a,b,c){browser.runtime.lastError;if(a.f){c||(a.f=!1);var d=this.g,e=this.f,f=this.l,g,h,k;for(k in d)if(g=d[k],g.port===a)g.a&&this.T(k),delete d[k];for(k in e)(h=e[k],h.port!==a||h.g)||(delete e[k],r&&delete e[h.id]);for(k in f)f[k].port===a&&delete f[k];this.ya===a&&U(this,63,!1);if(!c)if(c=a.tabId,d=a.Z,a.a&&delete this.a[c],delete this.a[[c,d]],delete this.u[a.id],r&&!b)browser.tabs.executeScript(a.tabId,{code:"__idm_connect__ && __idm_connect__(); true;"},V);else for(k in a=[c,
d].toString(),b=this.h,b)a==b[k].a&&delete b[k]}};
m.Ua=function(a,b){switch(b[0]){case 21:var c=b[1];c&&(a.j=c,null==a.Z&&this.ka(a));break;case 22:var d=this.a,e=d[[a.tabId,b[2]]];e&&(e.Pa=b[3],c=e.h=b[4],d=d[e.b])&&(d=d.h)&&(c[0]+=d[0],c[1]+=d[1],c[2]=Math.min(c[2]+d[0],d[2]),c[3]=Math.min(c[3]+d[1],d[3]));break;case 23:var c=a.A,f=a.tabId,g=b[1],d=b[2],e=b[4],h=this.b[c];if(g){if(g=I(this,g)){var h=f==h.v&&!h.G,k=!d||!e;k&&(d=f);if(f=b[7])g[101]||g.b&&g.R&&g.b!=g.R||(g.b=f),g.R=f;var f=Ka(this,d,a,k?null:b[5],k?null:b[6]),l=h&&!f.a;f.a=h?1:2;
g instanceof F&&W(this,g,2,(h?128:64)|(k?512:0),c,d,g.b);k||(Ya(this,d,e),l&&window.setTimeout(this.da.bind(this,c),3E3))}}else b[3]?(this.T(d,!0),delete this.g[d]):e&&f==h.v&&!h.G&&Ya(this,d,e,!0);break;case 24:c=b[2];(d=this.l[b[1]])&&c&&(d[101]||d.b&&d.R&&d.b!=d.R||(d.b=c),d.R=c);break;case 25:Ka(this,b[1],a,b[2],b[3]);break;case 26:Ua(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(c=this.l[b[1]]){d=c.L;if(e=b[4])if("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array){if(g=b[5])for(h=
0;h<e.length;h++)e[h][4]=g;Aa(d,e)}b[3]&&(c.f+=b[3]);b[6]&&(c.Y=b[6]);b[7]&&(c.R=b[7]);++c.M<c.C||(I(this,c.c),c.W?(d=this.b[c.port.A])&&d.v==c.tabId&&c.f&&(e=c.K,g=d.border,h=d.scale,J(this,10,1,0,[4294967295,d.A,Math.round(c.D*e+(d.fa+g)*h),Math.round(c.F*e+(d.va+g)*h),0,c.f]),this.i=c.tabId,Wa(this,c.tabId,[13,!0])):d.length?this.Ka(d,c.J,c):ab(c.tabId,"cannot_find_links"))}break;case 28:this.T(4294967295);break;case 29:bb(this,a.A,a.tabId);break;case 30:bb(this,a.A,a.tabId,b[1],b[2]);break;case 31:(c=
xa[b[1]])&&U(this,c,b[2],a);break;case 32:0==b[1]&&U(this,32,b[2],a);break;case 33:U(this,63,!1);break;case 34:c=b[2];d=b[3];e=b[4];b[1]&&(g=a.i)&&(g=[g,d||0],h={},k=32,h[110]=c,h[115]=e,-2==d&&(k|=16),J(this,16,1,k,g,h));break;case 35:c=b[2];d=b[3];(e=I(this,b[1]))&&this.ca(e.I,e.V,e.Y,e.g,c,d);break;case 36:e=b[1];c=b[2];if(d=this.f[e])e=[e,0],g={},g[115]=c,J(this,16,1,48,e,g),d.u=!1,d.C&&X(this,d);break;case 37:J(this,19,1,0,[b[1],b[2],a.tabId],b[3])}};
m.Ea=function(a){var b=a.l,c=a.w,d=a.g,e=a.a,f;if(1==b){var g=e[0];if(f=this.D[g])b=f.l,delete this.D[g]}switch(b){case 3:var d=e[0],h=this.F;0<=h&&(this.F=-1,h%=x.length+1,4<=d&&h<x.length&&(this.I="http://"+x[h]+"/status/204+IDM"));this.W=a[13]||"m"+e[2];if(a=e[4])a/=96,p&&(a=620756992>v?1:620756992<=v&&621284967>v?a:637534208<=v&&638078312>v?a:1.24<a?a:1),this.N=a,this.xa();this.ea&&this.ha();break;case 4:f=this.c;f[-9]=0<(d&64);f[-8]=0<(d&32);f[-4]=0<(d&2);f[-11]=0<(d&256)||2>c;f[-12]=0<(d&512)||
2>c;f[-1]=e[0];f[-2]=e[1];f[12]=a[12];f[17]=a[17];S(this,a,1);S(this,a,2);S(this,a,3);S(this,a,4);S(this,a,10);S(this,a,9,!0);S(this,a,11,!0);d=this.c;(e=a[18])?(h=e.replace(/(?:([A-Z]+)!)?.*?(\||$)/g,"$1$2").split("|"),e=e.replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=:\/\/)/g,"\\w*").replace(/\*(?!:\/\/)/g,".*?").replace(/(^|\|)[A-Z]+!/g,"$1").replace(/(:\/\/[^/]*?)~/g,"$1(?:\\b[^./]+?\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.*)?"),e="^(?:("+e.replace(/\|+/g,")|(")+"))$"):e="(?!)";d[18]=e=new RegExp(e);
e.fb=h;if(a=a[13])this.W=a;Ha(this);this.L||(this.L=!0,p&&browser.browserAction.enable(),this.s(1,browser.runtime.onConnect,this.Ta),this.s(1,browser.webNavigation.onCommitted,this.Fa),this.s(1,browser.webNavigation.onHistoryStateUpdated,this.Ra),a=t?void 0:y,d=["requestBody","blocking"],e=["requestHeaders","blocking"],h=["requestHeaders"],c=["responseHeaders","blocking"],f=["responseHeaders"],p&&1207959552<=v&&(e.push("extraHeaders"),1208887889<v&&1225679651>v&&h.push("extraHeaders")),this.w?(this.s(2,
browser.webRequest.onBeforeRequest,this.pa,{urls:["*://*/*"],types:a},d),this.s(2,browser.webRequest.onBeforeSendHeaders,this.qa,{urls:["*://*/*"],types:a},e),this.s(2,browser.webRequest.onHeadersReceived,this.ra,{urls:["*://*/*"],types:a},c)):(this.s(2,browser.webRequest.onBeforeRequest,this.pa,{urls:["http://*/*"],types:ga},d),this.s(2,browser.webRequest.onBeforeRequest,this.pa,{urls:["https://*/*"],types:a},d),this.s(2,browser.webRequest.onBeforeSendHeaders,this.qa,{urls:["http://*/*"],types:a},
h),this.s(2,browser.webRequest.onBeforeSendHeaders,this.qa,{urls:["https://*/*"],types:a},e),this.s(2,browser.webRequest.onHeadersReceived,this.ra,{urls:["http://*/*"],types:a},f),this.s(2,browser.webRequest.onHeadersReceived,this.ra,{urls:["https://*/*"],types:a},c)),this.s(3,browser.webRequest.onResponseStarted,this.cb,{urls:["*://*/*"],types:a}),this.s(3,browser.webRequest.onErrorOccurred,this.bb,{urls:["*://*/*"],types:a}),this.s(3,browser.webRequest.onBeforeRequest,this.ab,{urls:(this.c[17]||
"*://*.internetdownloadmanager.com/autoreg.html?*|*://*.internetdownloadmanager.com/fillregform.html?*").split("|"),types:ga},["blocking"]),browser.tabs.query({url:la[0]},this.la));break;case 18:f=this.c;if(1==e[0]){S(this,a,101,!0);ra=f[101];for(var k in a)(k=parseInt(k))&&110<k&&150>k&&(f[k]=a[k])}break;case 5:a=e[0];(e=this.b[a])?(d=0!=(d&128),e.G!=d&&(e.G=d)&&Za(this,a)):this.Ha(a);break;case 6:if(d&4)break;a=f.a[0];d=e[1];if(e=this.b[a])e.$=d,Xa(this,a);break;case 8:a=e[0];d&=32;if(4294967295==
a)Wa(this,this.i,[13,!1]),this.i=null;else if(a=this.g[a])a.a=d?0:2;break;case 11:a=e[0];4294967295==a&&(Ua(this,this.i,!0,!0),this.i=null);break;case 12:try{var l=a.a[5],n=a[4],d=4==l?2:3;if((1==l||2==l)&&Qa(this,a)){if(this.c[3].test(n))1==l?d=4:l=4;else if(this.c[-4]||this.c[4].test(n))d=4;a[8]|=256}if(4==l){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Ja(a)}else W(this,a,d)}catch(q){W(this,a,0)}break;case 13:a=f.a[0];d=f.a[5];e=e[1];if(1==
d||2==d)X(this,a,null,3==e);else if(5==d)if(e){if(a=(h=this.f[a])&&h.i){c=h.method;d=h.requestHeaders;if(e=h.b)(e=cb(e,Y(d,"Content-Type")))||(c="GET");a.timeout=1E4;a.onreadystatechange=this.Va.bind(this,a,h.id);a.open(c,h.url,!0);for(h=0;h<d.length;h++)c=d[h],f=c.name,0<=ha.indexOf(f.toLowerCase())&&(f="X-IDM-"+f),a.setRequestHeader(f,c.value);a.send(e)}}else db(this,a);break;case 1:break;default:!f&&d&1&&J(this,1,1,0,[a.m,0,0,0])}};
m.Ja=function(a,b,c){try{if(null==a.o)if(!b){var d=new L(this,a,!0);this.Ca(a,null,d)||browser.windows.getLastFocused(O(d,2));if(P(d))return}else if(c){var e=this.b[c.id],f=this.a[e&&e.v];f&&(a.o=f.id)}f=this.u[a.o];if(!f)return W(this,a,0);var g;var h=a.c;h||(h=Ba.prototype.u++,a.c=h,this.l[h]=a);g=h;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,g])}var l=[15,g,null,a[6],a[17],a[50],a[31]];f.a||Va(this,f,g);f.postMessage(l)}catch(n){W(this,a,0)}};
function W(a,b,c,d,e,f,g){-1!=c&&(e=[b.m,c,e,f],f={},f[8]=b[8],g&&(f[110]=g),J(a,1,1,d|(0==c?4:2),e,f))}m.Fa=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=this.a[[c,d]];f?b?e!=f.j&&(this.ba(f,!1,!0),f.j=e,f.l++,f.postMessage([17,!1,f.c])):this.ba(f,!0):0<d&&"about:blank"==e&&(Ma(this,c,d,a.parentFrameId),this.la(c))};m.Ra=function(a){return this.Fa(a,!0)};
m.Ga=function(a){var b=a.id;a={A:b,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.N,border:8,va:da,fa:0,sa:0,Da:"maximized"==a.state,ma:"minimized"==a.state,G:"fullscreen"==a.state,ta:0,ua:0,v:0,na:!t,$:null,H:null};this.b[b]=a;browser.tabs.query({windowId:b,active:!0},this.S);browser.tabs.query({windowId:b,url:la[0]},this.la);return a};m.Ha=function(a){J(this,5,1,32,[a]);delete this.b[a]};m.eb=function(a){if(0<a){var b=this.b[a];b&&(b.$||$a(this,b,!0),r&&this.wa(a,!1,!0,500))}};
m.$a=function(a,b,c){var d=c.windowId,e=this.b[d];e&&(e.$||$a(this,e),e.v||this.S(c));"complete"==b.status&&(a=this.a[a])&&!a.g&&(a.g=!0,this.da(d))};m.Za=function(a){var b=this.a,c=a.toString()+",";(a=b[a])&&this.ba(a,!0);for(var d in b)d.startsWith(c)&&this.ba(b[d],!0)};m.Xa=function(a){this.K=0;this.i&&this.T(4294967295);var b=a.windowId;a=a.tabId;var c=this.a[a];c&&!c.windowId&&(c.windowId=b);if(c=this.b[b])T(this,c.v),c.v=a,browser.tabs.get(a,this.S),this.da(b)};
m.Ya=function(a,b){var c=b.newWindowId,d=this.u,e;for(e in d)(e=d[e])&&e.tabId==a&&(e.A=c);T(this,a,!0)};function bb(a,b,c,d,e){a.i&&a.T(4294967295);var f=a.b[b];f&&f.v==c&&(d&&(f.ua=d),e&&(f.ta=e),T(a,c),a.wa(b,d||e,!1,250))}function db(a,b){var c=a.f[b];if(c){var d=c.i;c.u=!1;c.i=null;c.C&&X(a,c);d&&d.abort()}}m.Va=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);J(this,16,1,48,c,d);db(this,b)}};
function eb(a,b){var c=a.w||b.c&128;if(c&&b.h)return b.m=3,b.a|=2052,3;var d=a.c,e=new URL(b.url),f=fb(e.pathname);if(b.w&&f&&!e.search&&d[2].test(f))return 1;if(b.l)return 4;var g=d[9],h=d[1];if(b.w&&d[-9]){var d=d[18],k=d.exec(e.href);if(k&&!g.test(e.hostname))for(var l=1;l<k.length;l++)if(k[l]){d=d.fb[l-1];k=!1;l=0;d.includes("G")&&(k=!0,l|="GET"==b.method);d.includes("P")&&(k=!0,l|="POST"==b.method);if(k&&!l)break;if(d.includes("T")&&!h.test(f))break;b.m=3;b.a|=16777224;return 3}}return c&&t&&
!b.f&&!e.search&&!g.test(e.hostname)&&h.test(f)?(b.m=1,b.a|=8,5):4}
function gb(a,b){if(b.M)return a.aa(b,6),1;var c=b.h,d=b.statusCode;if(!c&&200!=d&&206!=d)return 1;var e=a.c,f=b.url,d=b.f,g=Y(b.responseHeaders,"Content-Type"),h=Y(b.responseHeaders,"Content-Disposition"),k=hb(g).toLowerCase(),l="attachment"==hb(h).toLowerCase();if(b.w&&!l&&"text/html"==k&&!c){if(b.g){if(c=a.h[[b.tabId,b.frameId]])c.c=!0;a.aa(b,5)}return 1}if(b.l||!d&&!e[-9])return 1;var n=c,q=!1,A=!1,D=!1,w=!1,Oa=!1,f=new URL(f),K=f.hostname,E=f.pathname,h=(g=ib(h,"filename")||ib(g,"name"))&&fb(g),
z=!1,Z=!1;if(g)if(h||c)z=Z=!0,b.F=g;else if(!d)return 1;Z||(g=E.split("/").pop(),(h=fb(g))&&h.toLowerCase()==k.split("/").pop()&&(z=!0));if(!z){var M=za[k];if(M)if(M=M.split("|"),h&&0<=M.indexOf(h))z=!0;else if(d||!h)h=M.shift(),z=!0;!h||z||!l&&k&&!e[10].test(k)||(z=!0)}if(!c){if(d&&ra.test(K))if("/videoplayback"==E)q=z=!0;else if(E.startsWith("/api/timedtext")&&"text/xml"==k)A=!0;else if(E.endsWith("/watch")&&0<parseInt(f.searchParams.get("pbj"))&&"application/json"==k)Oa=!0;else{if(E.endsWith("/get_video_info")&&
"application/x-www-form-urlencoded"==k||E.endsWith("/api_video_info")&&"application/x-www-form-urlencoded"==k||E.startsWith("/api/manifest/dash")&&"video/vnd.mpeg.dash.mpd"==k)D=!0}else d&&ta.test(K)?(K=ua.exec(E))&&"application/x-javascript"==k&&((k=va.exec(b.port.j))&&K[1]!=k[1]||(D=!0)):d&&sa.test(K)&&("M4S"==h&&(z=!0),"player.vimeo.com"==K&&E.startsWith("/video/")&&"application/json"==k&&(D=!0));d&&z&&("M3U8"==h||"F4M"==h?D=!0:"F4F"==h&&(g.endsWith("Seg1-Frag1")||g.endsWith("Seg1-Frag2")||g.includes("Seg1-Frag2_"))&&
(w=!0));z&&(d&&e[3].test(h)?q=!0:e[1].test(h)&&(n=d?!e[-4]&&!e[4].test(h):!0))}n&&!c&&(k=e[9])&&k.test(f.hostname)&&(n=!1);if(q){var N,Pa;if(k=e[11])k.test(f.hostname)?q=!1:(N=b.frameId?a.a[b.tabId]:b.port)&&(Pa=N.j)&&k.test((new URL(Pa)).hostname)&&(q=!1)}D||w?"POST"!=b.method||b.b?(N=new XMLHttpRequest,N.responseType=w?"blob":"text",b.i=N,A=!0):A=!1:Oa&&(A=b.u=!0);if(!n&&!q&&!A)return 1;z&&(b.K=h);Z&&(b.F=g);b.g|=A;b.m=n?2:q?4:5;b.a|=c?2052:q||A?256:(d?4096:0)|(Z||l?0:8388608)|16;return n?3:q?2:
4}
m.aa=function(a,b,c,d,e){var f=a.c,g=a.requestHeaders;if(null==d&&1==(f&31)&&(e=Y(g,"Cookie"),null==e))return Q(a.url,Ra(this,a,b,c,!0)),!0;"object"==typeof e&&(e=R(e));null==b&&(b=a.m);null==c&&(c=0);var h=a.id,k=a.port&&a.port.id,l=a.timeStamp;d=a.responseHeaders;var n=a.I,q=a.a;f&64&&(q|=2097152);"POST"==a.method&&(q|=512);t&&4>b&&(c|=1);a.g&&a.i&&(c|=1);a.g&&5!=b&&(c|=16);a.f&&(c|=16);b=[h,k,Math.floor(l/1E3),Math.floor(l%1E3*1E3),f&31,b];f={};f[6]=Sa(a.url);f[17]=a.P;f[4]=a.K;f[100]=a.F;f[8]=q;
f[11]=jb(g);f[13]=jb(d);f[18]=jb(n);a.b&&(f[14]=cb(a.b,Y(g,"Content-Type")));a.D&&(f[19]=cb(a.D,Y(n,"Content-Type")));if(null==g){g=this.h;d=[a.tabId,a.frameId];do d=(n=g[d])&&n.a,n=n&&n.j,"about:blank"==n&&(n=null);while(!n&&d);f[50]=n;f[51]=e;f[54]=navigator.userAgent}if(a=this.a[a.tabId])f[7]=a.j,f[110]=a.title;return J(this,13,1,c,b,f)};
function X(a,b,c,d){var e=a.f,f,g;"object"==typeof b?f=b.requestId:(f=b,b=e[f]);if(d)if(0>b.tabId)g={cancel:!0};else if(p&&c&&587202560>v)g=[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}],g={responseHeaders:g};else if(p||(t?c&&939524096>v:c)){g=a.I;if(r||!g){g=na;var h=a.h[[b.tabId,b.frameId]];h&&!h.f&&(g+="?back=1")}g={redirectUrl:g}}else g={cancel:!0};if(b){c&&c.ip&&(b.a|=c.ip.includes(":")?4194304:0);(c=b.resolve)&&void 0!==
d&&(b.resolve=b.reject=null,c(g||{}));if(d=b.reject)b.resolve=b.reject=null,d();!b.m||b.C||c||d||a.aa(b);if(b.i||b.u)return b.C=!0,g;delete e[f];r&&delete e[b.id];b.f&&(e[b.id]={url:b.url,port:b.port})}return g}m.ab=function(a){var b=a.url,c=new URL(b);if(c.search.startsWith("?d="))return a=this.a[a.tabId],this.ca("idmreg:"+b.substr(c.protocol.length),null,a&&a.j),{redirectUrl:na+"?register=1"}};
m.pa=function(a){if(!(t&&0>y.indexOf(a.type))){var b=a.tabId,c=a.frameId;if(!(0>b||0>c)){var d=a.requestId,e=a.url,f=Ta(e),g=a.type.endsWith("_frame"),h="POST"==a.method;if(g){var k=Ma(this,b,c,a.parentFrameId);k.b!=d&&(k.b=d,k.g=e,k.c=!1);k.f=h}if(g||this.w||f&128){var e=this.J,k=this.V,l=!0;if(!k&&h&&a.requestBody){var h=a.requestBody,n=h.raw;if(n)for(var q=0;q<n.length&&(n[q].bytes||(n=null));q++);n||h.formData||p&&h.error?(d=this.f[d])?d.requestBody=h:La(this,a):l=!1}if(g||e&&l)switch(a.h=e,a.l=
k,a.c=f,a.w=g,a.f=0<=B.indexOf(a.type),a.b=a.requestBody,a.port=this.a[[b,c]],eb(this,a)){case 5:if(t)return new Promise(this.La.bind(this,a));case 3:return X(this,a,null,!0)}}}}};
m.qa=function(a){if(!(t&&0>y.indexOf(a.type))){var b=a.tabId;if(0<b){var c=a.requestId,d=a.url,e=a.method,f=Ta(d);if(!f||"GET"!=e&&"POST"!=e)return X(this,a);a.h=this.J;a.l=this.V;var g=0;if(c=this.f[c]){a.id=c.id;a.port=c.port;a.b=c.requestBody;if(g=c.J||0)a.P=c.P||c.url,a.I=c.I||c.requestHeaders,a.D=c.D||c.b,a.h=c.h,a.l=c.l;!t||302!=c.statusCode&&303!=c.statusCode||(a.method=e="GET")}var c=a.type,h=c.endsWith("_frame");if(!a.port&&!(a.port=this.a[[b,a.frameId]])&&!h||"POST"==e&&(!a.b||a.b.error&&
0<Y(a.requestHeaders,"Content-Length")))return X(this,a);d.includes("#")&&(a.url=Sa(d));a.J=++g;a.c=f;a.w=h;a.f=0<b&&0<=B.indexOf(c);a.g=qa.test(d);switch(eb(this,a)){case 5:if(t)return new Promise(this.La.bind(this,a));if(!a.h)break;case 3:return X(this,a,null,!0);case 1:return X(this,a)}La(this,a)}else if("xmlhttprequest"==a.type&&(a.L?a.L==oa:a.N?a.N==pa:1)){a=a.requestHeaders;b={};d=!1;for(e=0;e<a.length;e++)f=a[e],g=f.name.toLowerCase(),g.startsWith("x-idm-")?b[g.substr(6)]=d=!0:"origin"==g&&
f.value==oa&&(b[g]=d=!0);if(d){for(e=0;e<a.length;e++)f=a[e],g=f.name.toLowerCase(),b[g]?a.splice(e--,1):g.startsWith("x-idm-")&&(f.name=f.name.substr(6));return{requestHeaders:a}}}return null}};m.La=function(a,b,c){a.resolve=b;a.reject=c;La(this,a);this.aa(a)};
m.ra=function(a){if(!(t&&0>y.indexOf(a.type))){var b=this.f[a.requestId];if(b){var c=a.responseHeaders;if("image"==b.type){var d=Y(c,"Content-Type");if(d&&d.toLowerCase().startsWith("image/"))return X(this,b)}"quic"==Y(c,"Client-Protocol")?b.c|=64:(d=Y(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Y(c,"Transfer-Encoding")&&(b.c|=64);if(this.w||b.c&192)switch(d=b.statusLine=a.statusLine,d=b.statusCode=a.statusCode||parseInt(d.split(" ",2).pop()),b.M=0<=ia.indexOf(d),b.responseHeaders=
c,gb(this,b)){case 3:return X(this,b,a,!0)}if(b.u)return c.push({name:"X-IDM-Request-ID",value:b.id.toString()}),{responseHeaders:c}}}};m.cb=function(a){if(!(t&&0>y.indexOf(a.type))){if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){var b=this.h[[a.tabId,a.frameId]];b&&(b.j=a.url,b.P=b.g)}(b=this.f[a.requestId])&&X(this,b,a)}};m.bb=function(a){t&&0>y.indexOf(a.type)||X(this,a.requestId)};
m.ha=function(a,b,c,d,e){if(void 0===a&&(this.ea=!1,a=new L(this,!0),browser.storage.local.get("version",O(a,1)),(r?1073741824<=v:p)&&browser.extension.isAllowedIncognitoAccess(O(a,2)),p&&browser.management.get("jeaohhlajejodfjadcponpnjgkiikocn",O(a,3)),u&&"ngpampappnmepgilojfohadhhmbhlaek"!=browser.runtime.id&&browser.management.get("ngpampappnmepgilojfohadhhmbhlaek",O(a,4)),P(a)))return;a=browser.runtime.getManifest();a=a.version||"";"object"==typeof b&&(b=b.version||"");c=null!=c&&!c;"object"==
typeof d&&(d=d.enabled&&d.id);d&&browser.management.setEnabled(d,!1);"object"==typeof e&&(e=e.enabled&&e.id);e&&browser.management.setEnabled(e,!1);a&&a!=b&&null!=b&&(browser.storage.local.set({version:a}),d=this.W,e="v6.32">d,b&&d&&!e||(a="current="+escape(a),b&&(a+="&previous="+escape(b)),c&&(a+="&incognito=1"),d&&(a+="&manager="+escape(d)),e&&(a+="&update=1"),r&&(a+="&msedge=1"),t&&(a+="&mzffox=1"),u&&(a+="&opera=1"),browser.tabs.create({url:browser.runtime.getURL("welcome.html?"+a)})))};
function ab(a,b){var c=browser.i18n.getMessage(b);t?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(c)+'")); true;'},V):window.alert(c)}m.s=function(a,b,c){var d=C(arguments);if(t||r)d[2]=function(){return c.apply(null,arguments)};this.Aa.push(d);b.addListener.apply(b,d.slice(2))};function L(a,b){this.caller=arguments.callee.caller;this.c=a;this.b=C(arguments,1);this.a=0;this.g=this.f=!1}function O(a,b){a.a++;return a.i.bind(a,b)}
function P(a){return a.a?a.f=!0:a.g?(a.caller.apply(a.c,a.b),!0):!1}L.prototype.i=function(a,b){browser.runtime.lastError;this.b[a]=b;0==--this.a&&(this.f?this.caller.apply(this.c,this.b):this.g=!0)};L.prototype.h=function(a,b,c){var d=C(arguments,3);c&&(d=c.concat(d));a.apply(b,d);this&&0==--this.a&&this.caller.apply(this.c,this.b)};function Ra(a){var b=C(arguments,1),c=b[b.length-1];c instanceof L?c.a++:c=null;return L.prototype.h.bind(c,arguments.callee.caller,a,b)}
function Ja(a){return browser.i18n.getMessage(a)||a}function Sa(a){var b=a.lastIndexOf("#");return 0>b||b<a.indexOf("?")?a:a.substr(0,b)}function R(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}function jb(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}
function Y(a,b){if(!a)return null;b=b.toLowerCase();for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function ib(a,b){if(!a)return null;var c,d,e=a.split(";");for(b=b.toLowerCase();e.length;){var f=e.shift(),g=f.indexOf("=");if(0<g){var h=f.substr(0,g).trim().toLowerCase(),k="*"==h[h.length-1];if(k)h=h.substr(0,h.length-1).trimRight();else if(d)continue;if(h==b)if(f=f.substr(g+1).trim(),g=f.length-1,'"'==f[0]&&'"'==f[g]&&(f=f.substring(1,g)),k){if(f=f.split("'",3),k=f.shift().toLowerCase(),(g="utf-8"==k||"utf8"==k)||!d)if(c=unescape(f.pop()),d=k,g)break}else c=unescape(f)}else 0>g&&null==c&&f.trim().toLowerCase()==
b&&(c="")}return c}function hb(a){var b=/[;,]/;return a&&(a=a.split(b,1).shift().trim())&&0>a.indexOf("=")&&unescape(a)||""}
function cb(a,b){var c=a.raw;if(c){for(var d=String.fromCharCode,e="",f=0;f<c.length;f++){var g=c[f].bytes;if(!g)return null;for(var g=new Uint8Array(g),h=g.length,k=0;k<h;k++)e+=d(g[k])}return e}c=a.formData;if(!c)return null;f=hb(b).toLowerCase();e=[];if(f&&"application/x-www-form-urlencoded"!=f)if("multipart/form-data"==f){(g=ib(b,"boundary"))||(g="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(h=c[d],f=0;f<h.length;f++)e.push("--",g,'\r\nContent-Disposition: form-data; name="',
d,'"\r\n\r\n',h[f],"\r\n");e.push("--",g,"--\r\n")}else return null;else for(d in c)for(h=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<h.length;f++)e.length&&e.push("&"),e.push(d,"=",h[f].split(" ").map(encodeURIComponent).join("+"));return e.join("")}function fb(a){return(a=ma.exec(a))?a.pop().toUpperCase():""}function Ta(a,b){var c=a.split(":",1).shift().toLowerCase(),c=ya[c]||0;return b?c&31:c}
function kb(a){if(void 0===a){var b=navigator.userAgent;a=b.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);if(b=t?a:b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/)){v=b[1]<<24|b[2]<<22|b[3]<<8|b[4];aa=b[0];ba=a?a[0]:b[0];browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(kb);try{t&&browser.privacy.websites.firstPartyIsolate.get({},kb)}catch(c){}browser.webRequest.ResourceType&&browser.webRequest.ResourceType.MEDIA&&y.push("media")&&B.push("media");
t&&y.push("object_subrequest")&&B.push("object_subrequest")}}else"version"in a?(b=a.version.split(/\D+/),v=b[0]<<24|b[1]<<22|b[2]<<8|b[3],aa=ba=a.name+"/"+a.version):"value"in a&&(ca=a.value)}function V(a){browser.runtime.lastError;a}
var Ia=[[!0,-11,"menu_download_link","link,image",H.prototype.ja],[!0,-11,"menu_download_link","page,frame,editable",H.prototype.ja,ka],[!0,-11,"menu_download_selected","selection",H.prototype.Ba],[!0,-12,"menu_download_all","page,frame,editable",H.prototype.Ba],[p,-11,"menu_download_item","link",H.prototype.ja,["chrome://downloads/*"]]];String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(b||0,a.length)===a});
String.prototype.endsWith||(String.prototype.endsWith=function(a,b){b=(null==b||b>this.length?this.length:b)-a.length;return 0<=b&&this.lastIndexOf(a,b)==b});String.prototype.includes||(String.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});kb();new H;
